FROM ubuntu:22.04

LABEL maintainer="Taylor Otwell"

ARG WWWGROUP
ARG NODE_VERSION=20
ARG POSTGRES_VERSION=15

# Önce çalışan kullanıcı ve grup oluşturuluyor
RUN groupadd --force -g $WWWGROUP sail \
    && useradd -ms /bin/bash --no-user-group -g $WWWGROUP -u 1337 sail

# Gerekli paketlerin yüklenmesi
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    gnupg gosu curl ca-certificates zip unzip git supervisor sqlite3 libcap2-bin libpng-dev python2 dnsutils librsvg2-bin fswatch \
    software-properties-common

# Paket listelerini temizleme
RUN rm -rf /var/lib/apt/lists/*

# PHP ve ek modüllerin yüklenmesi
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    php8.3-cli php8.3-dev \
    php8.3-pgsql php8.3-sqlite3 php8.3-gd \
    php8.3-curl \
    php8.3-imap php8.3-mysql php8.3-mbstring \
    php8.3-xml php8.3-zip php8.3-bcmath php8.3-soap \
    php8.3-intl php8.3-readline \
    php8.3-ldap \
    && rm -rf /var/lib/apt/lists/*

# Composer'ın yüklenmesi
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer

# Node.js ve npm'nin yüklenmesi
RUN curl -fsSL https://deb.nodesource.com/setup_$NODE_VERSION.x | bash - \
    && apt-get install -y --no-install-recommends nodejs \
    && npm install -g npm pnpm bun \
    && rm -rf /var/lib/apt/lists/*

# Yarn'ın yüklenmesi
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | tee /usr/share/keyrings/yarn-archive-keyring.gpg >/dev/null \
    && echo "deb [signed-by=/usr/share/keyrings/yarn-archive-keyring.gpg] https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends yarn \
    && rm -rf /var/lib/apt/lists/*

# PostgreSQL ve diğer paketlerin yüklenmesi
RUN curl -sS https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | tee /usr/share/keyrings/pgdg.gpg >/dev/null \
    && echo "deb [signed-by=/usr/share/keyrings/pgdg.gpg] http://apt.postgresql.org/pub/repos/apt jammy-pgdg main" > /etc/apt/sources.list.d/pgdg.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
    postgresql-client-$POSTGRES_VERSION mysql-client \
    && rm -rf /var/lib/apt/lists/*

# Belirli bir yetkiyi verme
RUN setcap "cap_net_bind_service=+ep" /usr/bin/php8.3

# İlgili dosyaların kopyalanması
COPY start-container /usr/local/bin/start-container
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY php.ini /etc/php/8.3/cli/conf.d/99-sail.ini

# Dosyaların izinlerinin ayarlanması
RUN chmod +x /usr/local/bin/start-container

# 8000 portu açılıyor
EXPOSE 8000

# Giriş noktası belirleniyor
ENTRYPOINT ["start-container"]
